name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore StereoKit.DesktopMirror\StereoKit.DesktopMirror.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore StereoKit.DesktopMirror\StereoKit.DesktopMirror.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal StereoKit.DesktopMirror\StereoKit.DesktopMirror.csproj
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
